### ISSUE TITLE
when recieving a direct message page crashes with error

### ISSUE THREAD

**Issue by Gotr-byte** [Gotr-byte/Transcendence#53]
![image](https://github.com/Gotr-byte/Transcendence/assets/82155525/a219cc60-1573-4af8-9499-42e951030258)

**Comment by Gotr-byte** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: object with keys {id, username}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19167:28)
    at updateHostComponent (react-dom.development.js:19924:3)
    at beginWork (react-dom.development.js:21618:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
2hooks.tsx:513 Error handled by React Router default ErrorBoundary: Error: Objects are not valid as a React child (found: object with keys {id, username}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19167:28)
    at updateHostComponent (react-dom.development.js:19924:3)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:74)
DefaultErrorComponent @ hooks.tsx:513
react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: object with keys {id, username}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19167:28)
    at updateHostComponent (react-dom.development.js:19924:3)
    at beginWork (react-dom.development.js:21618:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
2hooks.tsx:513 Error handled by React Router default ErrorBoundary: Error: Objects are not valid as a React child (found: object with keys {id, username}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19167:28)
    at updateHostComponent (react-dom.development.js:19924:3)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
DefaultErrorComponent @ hooks.tsx:513
react-dom.development.js:18687 The above error occurred in the <div> component:

    at div
    at div
    at DirectMessageSenderList (http://localhost:5173/src/components/Chat/DirectMessages.tsx:21:33)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at Flex2 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:17683:11)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at Flex2 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:17683:11)
    at ChatUI (http://localhost:5173/src/components/ChatUI.tsx:27:33)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at TabPanel2 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:27357:22)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at TabPanels2 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:27374:23)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at Tabs2 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:27288:18)
    at Chat
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ead749d0:3327:5)
    at Outlet (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ead749d0:3720:26)
    at main
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at GridItem2 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:17231:5)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2374:45
    at ChakraComponent (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10302:35)
    at Grid2 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:16875:5)
    at RootLayout (http://localhost:5173/src/layouts/RootLayout.tsx:26:39)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ead749d0:3327:5)
    at RenderErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ead749d0:3287:5)
    at DataRoutes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ead749d0:3648:5)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ead749d0:3727:15)
    at RouterProvider (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=ead749d0:3597:5)
    at App
    at EnvironmentProvider (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:1383:11)
    at ColorModeProvider (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2977:5)
    at ThemeProvider2 (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:2418:23)
    at ThemeProvider3 (http://localhost:5173/node_modules/.vite/deps/chunk-DGQYNPOM.js?v=faa789fc:10379:11)
    at ChakraProvider (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:1411:5)
    at ChakraProvider22 (http://localhost:5173/node_modules/.vite/deps/@chakra-ui_react.js?v=ea7c6a2e:10090:5)

React will try to recreate this component tree from scratch using the error boundary you provided, RenderErrorBoundary.
logCapturedError @ react-dom.development.js:18687
hooks.tsx:608 React Router caught the following error during render Error: Objects are not valid as a React child (found: object with keys {id, username}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19167:28)
    at updateHostComponent (react-dom.development.js:19924:3)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20) Object

**Comment by Gotr-byte** [comment]
I need to check with after merging with matchmaking where the new socket events are.

**Comment by Gotr-byte** [comment]
Problem was with messaging direct messages that were utilizing unimplemented endpoints.
